-- Roofing TX 2026-05-15 — generated by score_roofing.py + persist script
-- Run ID: ae0694e6-a997-4b9a-96b2-10cc75ca1d4b
-- Pre-emptive idempotent: delete signals + scores for this run first (in case of partial-prior-write)

DELETE FROM offmarket.business_signals
  WHERE business_id IN (
    SELECT id FROM offmarket.businesses WHERE vertical = 'roofing'
  );

DELETE FROM offmarket.business_scores
  WHERE score_run_id = 'ae0694e6-a997-4b9a-96b2-10cc75ca1d4b';

DELETE FROM offmarket.businesses WHERE vertical = 'roofing';
