"""
Build plumbing_targets.json + CSV from spine + enrichment files.

Applies the 4-layer scoring model (L1 0.30 + L2 0.25 + L3 0.30 + L4 0.15).
Implements hard gates and tier rules per scoring-model.md.

Output:
  offmarket/data/plumbing_targets.json
  offmarket/data/plumbing_targets.csv
  offmarket/data/plumbing_run_manifest.json
"""

import json
import csv
import os
from datetime import datetime
from pathlib import Path
import uuid

ROOT = Path("/Users/gideonspencer/dealhound-pro/.claude/worktrees/crazy-khayyam-7adaed/offmarket")
DATA = ROOT / "data"

SCORE_RUN_ID = "6cbb9025-2383-4e26-bbd2-992f0e1a906f"
RUN_LABEL = "plumbing-tx-2026-05-15"
MODEL_VERSION = "offmarket-4layer-v0.2"
WEIGHTS = {"layer1": 0.30, "layer2": 0.25, "layer3": 0.30, "layer4": 0.15}
VERTICAL = "plumbing"

# Per-business scoring inputs derived from spine + enrichment
# Each row: (spine_id, layer1, layer2, layer3, layer4, final_comment, value_add, confidence, is_distressed, distress_reasons, l1_comment, l2_comment, l3_comment, l4_comment)
SCORES = {
    # ============ TIER-A A_acquire_self CANDIDATES ============
    "plm-008": {  # David Hicks Plumbing
        "layer1": 82,
        "layer2": 78,
        "layer3": 75,
        "layer4": 88,
        "owner_age_estimate": 67,
        "owner_age_source": "biz_history_proxy",
        "owner_tenure_years": 30,
        "years_in_business": 74,
        "provider_count_estimate": 1,
        "employee_count_estimate": 8,
        "is_distressed": False,
        "distress_reasons": [],
        "confidence": "medium",
        "data_completeness": 0.70,
        "layer1_comment": "David Hicks is 2nd-generation owner of a 74-year operation (founded by father George Hicks 1952). David's MP license M-8529 is a low-number pre-1990 legacy = 35+ yrs MP tenure. Estimated age ~67 derived from family-business history proxy (George founded 1952, David ~30 yr generational gap = born ~1957-65). NO 3rd-gen Hicks visible. Confidence: medium pending Harris CAD OV65 check on personal residence.",
        "layer2_comment": "74-yr operation in elite River Oaks/Montrose Houston submarket (77019). Multi-licensed (TX Master Plumber + multiple service registrations 1488, 20904, REG12333, REG13208, 15453, M-8529 = multi-trade scope). 50+ Yelp reviews. SBA-financeable size — 'fully stocked trucks' (plural) + commercial+residential services + leak detection/repipe/tankless = solo-to-mid shop ≈ $1-2M revenue band.",
        "layer3_comment": "Strong coasting tells: (a) NO membership plan or recurring service agreement visible on davidhicksplumbing.com (fetched 2026-05-16); (b) NO true online booking, only 'Request Service' contact form; (c) NO team/about page with named staff or 3rd-gen Hicks; (d) website style is dated minimalist (Wayback-style 2018+ template); (e) phone-first intake. 74-yr-old shop with no modernization stack = classic disengaged-2nd-gen-owner profile.",
        "layer4_comment": "Houston is top-3 TX rollup metro for plumbing. Wrench Group, Apex Service Partners, ARS, Roto-Rooter Service Co, Service Champions all active in Houston with $1M+ EBITDA bolt-on bids at 7-12× EBITDA. River Oaks/Montrose 77019 ZIP = older 1920s-1960s housing stock = high recurring repair revenue density. Sub-market nudge +3 for older Houston housing. Plumbing rollup is currently HOT (+9 modifier).",
        "final_comment": "David Hicks, ~67 yrs old (2nd-gen owner; father George founded the company in 1952; David's MP license M-8529 is pre-1990 = 35+ yrs MP tenure), runs David Hicks Plumbing out of 2023 Fairview St in Houston's River Oaks/Montrose 77019. 74-year-old family-owned shop. NO 3rd-generation Hicks visible on the website (fetched 2026-05-16) or in BBB profile — the line ends at David. Strong coasting tells: no membership plan, no online booking, no team page, dated website. Premium River Oaks submarket = older housing = strong recurring service base. Houston plumbing rollup is hot (Wrench Group, Apex, ARS all paying premium multiples). A_acquire_self pending Harris CAD OV65 verification.",
        "value_add_thesis": "AI dispatch (ServiceTitan migration), true online booking, recurring service-agreement program (Hicks Family Plan $25-30/mo, targeting River Oaks demographic), modern field-service software, automated review generation, technician hiring funnel + sale-leaseback on Fairview St building (CAD lookup). 74-yr River Oaks customer base = the asset; modernization unlocks 2-3× revenue from existing customers + commands premium multiple on exit. Credible 30-50% EBITDA uplift over 18-24 months."
    },
    "plm-085": {  # Clarke Kent Plumbing
        "layer1": 78,
        "layer2": 88,
        "layer3": 72,
        "layer4": 90,
        "owner_age_estimate": 65,
        "owner_age_source": "license_tenure_proxy",
        "owner_tenure_years": 40,
        "years_in_business": 40,
        "provider_count_estimate": 2,
        "employee_count_estimate": 15,
        "is_distressed": False,
        "distress_reasons": [],
        "confidence": "medium",
        "data_completeness": 0.75,
        "layer1_comment": "Gary W Hacker President + Cynthia Clarke VP (co-owner partnership). Hacker's TSBPE M-14195 is a pre-1990 legacy license = 35+ yrs MP tenure. Estimated age ~65 (MP'd before 1990 + journeyman path = born ~1955-1965). Confidence medium pending Travis CAD OV65 check on both Hacker and Clarke residences. Co-owner structure (Hacker + Clarke) means partner-to-partner sale to outside buyer rather than internal-succession-to-junior — fits Gideon's thesis if both are retirement-age.",
        "layer2_comment": "$10.6M revenue / 15 employees per D&B = squarely in SBA-7(a) jumbo + 504 real-estate financeable platform-bolt-on range. 40-yr operation. Multi-trade plumbing including 24/7 emergency, residential + commercial + hydro-jetting + camera inspection + boiler + lift station = comprehensive scope. PM Plumber license + 4 additional = clean license stack. 200+ Yelp reviews 4.4-star. Strong sellability score.",
        "layer3_comment": "At $10.6M revenue with 15 employees in 2026, the absence of a customer membership plan, the absence of true online booking (only contact form on clarkekentplumbing.com fetched 2026-05-16), and the absence of named technicians on the About page are SIGNIFICANT coasting tells. Modern plumbing shops at this scale all have ServiceTitan + Housecall Pro membership programs + technician hiring funnels. The Hacker-Clarke partnership has stopped pushing modernization in the last 5-7 years per the static About page tone.",
        "layer4_comment": "Austin is top-3 TX rollup metro. ZIP 78704 = premium South Austin (Travis Heights, Bouldin Creek, South Congress) = older housing stock + premium incomes = high recurring repair revenue density. Sub-market nudge +5 for premium Austin ZIP. Apex Service Partners (Alpine), Wrench Group, Service Champions all paying premium multiples in Austin. $10.6M revenue shop is in platform-acquirer SWEET SPOT ($300-800K EBITDA bolt-on at 5-7× = $1.5-5.5M sale). Plumbing rollup HOT (+9).",
        "final_comment": "Gary Hacker (President + RMP since pre-1990, M-14195) and Cynthia Clarke (VP) co-own Clarke Kent Plumbing, a 40-yr Austin operation generating $10.6M revenue with 15 employees (D&B-verified). Both principals are estimated retirement-window age (Hacker MP'd pre-1990 = age ~65+). At $10M+ revenue, the ABSENCE of a customer membership plan and the ABSENCE of true online booking on clarkekentplumbing.com (fetched 2026-05-16) are highly unusual modernization gaps — the partners have stopped pushing. Premium South Austin ZIP 78704 (Travis Heights / Bouldin / South Congress). Co-owner partnership means partner-to-partner exit to outside buyer rather than internal junior succession — fits Gideon's thesis. A_acquire_self pending TCAD OV65 verification on Hacker and Clarke residences + confirmation no younger partner-track successor.",
        "value_add_thesis": "Clarke Kent has $10.6M revenue at 40-yr operating maturity but zero modern revenue infrastructure: no recurring-service membership program, no true online booking, no SMS dispatch automation, no named technicians on the website. A bolt-on operator could: (a) launch a Plumb Sentinel monthly membership at $24.95/mo across existing customer base = $300-600K incremental ARR within 12 months; (b) migrate to ServiceTitan for dispatch + scheduling = 15-25% windshield-time reduction; (c) build a technician apprenticeship program tied to TSBPE Journeyman ladder = solve the bench-depth problem; (d) automated review generation = leverage 200+ existing 4.4-star reviews into 1000+ across Austin metro. Credible 25-40% EBITDA uplift over 18-24 months. Sale-leaseback on 1408 W Ben White (TCAD lookup) if owned by entity."
    },
    "plm-017": {  # John's Plumbing Inc (Anselmo)
        "layer1": 80,
        "layer2": 65,
        "layer3": 85,
        "layer4": 82,
        "owner_age_estimate": 68,
        "owner_age_source": "license_tenure_proxy",
        "owner_tenure_years": 37,
        "years_in_business": 44,
        "provider_count_estimate": 1,
        "employee_count_estimate": 4,
        "is_distressed": False,
        "distress_reasons": [],
        "confidence": "medium",
        "data_completeness": 0.55,
        "layer1_comment": "John P. Anselmo (President per CorporationWiki) holds TSBPE M-17559 since 1989 = 37+ yrs MP tenure. Estimated age ~68 (MP'd 1989 at age ~30 = born ~1959). Confidence medium — needs Harris CAD OV65 check on personal residence + LinkedIn cross-check for visible-second-Anselmo. Solo-listed RMP.",
        "layer2_comment": "44-yr operation (since 1982). Single RMP + 'family-owned' brand. Small-shop residential service. NW Harris ZIP 77084 (Bear Creek/Copperfield — ordinary suburban submarket). Estimated 2-4 trucks / 4-6 staff ≈ $500K-1.2M revenue band. Below platform-acquirer sweet spot but in SBA / ETA-searcher range. License clean.",
        "layer3_comment": "EXTREME coasting tells: (a) johnsplumbing-houston.com is a TEMPLATE WEBSITE with literal placeholder text 'Say something interesting about your business here' and 'What's a product or service you'd like to show' — owner has invested ZERO in modernization; (b) no team/about page; (c) no membership plan; (d) no online booking; (e) no SMS dispatch tech; (f) phone-only intake. 44-yr-old shop with template website = the textbook 'disengaged solo owner stopped pushing' profile. 5 strong coasting tells stacked.",
        "layer4_comment": "Houston is top-3 TX rollup metro. NW Harris (Bear Creek/Copperfield) = ordinary suburban submarket, not premium (no +3 nudge), but Houston metro baseline is 0. Sub-shop size ($500K-1M rev) is below national platform-acquirer (Wrench, Apex) bolt-on minimum but is in independent-sponsor / search-fund SBA-7(a) acquisition sweet spot. Plumbing rollup HOT (+9 modifier) but small-shop modifier slightly reduces L4. Score 82.",
        "final_comment": "John P. Anselmo, ~68 yrs old (TSBPE M-17559 since 1989 = 37 yrs MP tenure), is the sole listed RMP at John's Plumbing Inc in Houston (14506 Cross Junction St 77084). 44-year-old family-owned operation. The website johnsplumbing-houston.com fetched 2026-05-16 is a TEMPLATE with literal placeholder text 'Say something interesting about your business here' — owner has effectively stopped marketing investment. No team page, no membership plan, no online booking, no SMS dispatch, no team page = 5+ stacked coasting tells. Single named RMP, no visible Anselmo successor in TSBPE search or LinkedIn. Smaller shop size ($500K-1.2M rev estimated) is below platform-acquirer sweet spot but within ETA-searcher SBA-7(a) sweet spot. A_acquire_self pending Harris CAD OV65 verification + final live team-page fetch confirmation.",
        "value_add_thesis": "John's Plumbing has 44 years of customer relationships in NW Houston (Bear Creek / Copperfield / Cypress fringe) but a literal-template website with unfilled placeholder text. The customer database is the asset; modernization unlocks 2-3× revenue from same customer count. Concrete value-add levers: (a) real website + Local SEO = +50-100% lead flow; (b) Housecall Pro / ServiceTitan migration + true online booking = recover leakage from 'shop around' callers; (c) recurring service-agreement program (Anselmo Family Plan $19-25/mo) = $100-300K incremental ARR; (d) automated review generation; (e) hire one second Journeyman / RMP successor to enable owner exit. Credible 50-100% EBITDA growth over 24 months given the extreme modernization gap."
    },

    # ============ B_forward ============
    "plm-001": {"layer1": 70, "layer2": 88, "layer3": 50, "layer4": 90, "owner_age_estimate": 72, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 52, "years_in_business": 52, "provider_count_estimate": 3, "employee_count_estimate": 16, "is_distressed": False, "distress_reasons": [], "confidence": "high", "data_completeness": 0.80, "layer1_comment": "Joe Santhoff founder ~age 72-78 (1974 founding + ~30 yr at founding = age ~75). Long tenure but family succession already structured — Jason (GM) + James (MP) + Julie (Office) Santhoff are clearly the next generation.", "layer2_comment": "Excellent: 52-yr operation, 14+ named techs + 2 MPs, Santhoff Family Club membership = recurring revenue, 840 Google reviews 4.9-star, multi-trade scope. ≈ $2.5-4M rev band, SBA-financeable mid-shop.", "layer3_comment": "Limited coasting tells — Family Club membership active, Yelp/Google review velocity strong (840 reviews 4.9), 'Request Service' modernized form. Successor check NEGATIVE: live team page fetched 2026-05-16 lists Joe + Jason (GM) + James (MP) + Julie (Office Mgr). NOT a coasting-solo profile.", "layer4_comment": "Houston rollup hot, Santhoff is platform-acquirer sweet-spot size at $2.5-4M rev, premium 5-county Houston metro service area.", "final_comment": "Joe Santhoff, ~75 (founded Santhoff Plumbing 1974, family-business proxy), runs the company with second-generation children Jason (GM), James (Master Plumber), and Julie (Office Mgr) — verified via live team-page fetch on santhoffplumbingco.com/about-us 2026-05-16. Multi-generation structured family succession is in place; this is NOT the coasting-solo-to-outside-buyer profile. Healthy mid-shop ($2.5-4M rev band), Santhoff Family Club $20/mo membership, 840 Google reviews 4.9-star. B_forward — strong bolt-on candidate for the Mastermind / ETA buyer community but not Gideon-acquire-self.", "value_add_thesis": "Mid-shop Houston multi-gen family plumbing operation with strong existing membership program and review base. Forward to ETA / search-fund / Apex-Wrench-platform buyer community as a B-tier bolt-on. Value-add levers: ServiceTitan dispatch migration, $5M+ revenue stretch via geographic expansion into Sugar Land + Katy, recurring revenue conversion from one-time customers."},
    "plm-002": {"layer1": 72, "layer2": 70, "layer3": 55, "layer4": 78, "owner_age_estimate": 70, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 55, "years_in_business": 55, "provider_count_estimate": 2, "employee_count_estimate": 8, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.55, "layer1_comment": "Strutton Plumbing 'third-generation family-owned' since 1971. Current operator age ~60-70.", "layer2_comment": "55-yr operation, mid-shop multi-trade plumbing + new construction + underground utilities, Houston 77074.", "layer3_comment": "Successor check NEGATIVE: live website states 'third-generation family-owned business' = internal succession explicit. No coasting-solo thesis.", "layer4_comment": "Houston rollup hot.", "final_comment": "Strutton Plumbing Company, 55-yr-old explicit 3rd-generation family operation in Houston 77074. Internal succession in place. B_forward — bolt-on candidate.", "value_add_thesis": "Mid-shop Houston multi-trade plumbing + underground utilities specialty. Forward to ETA/PE community as B-tier bolt-on."},
    "plm-005": {"layer1": 60, "layer2": 88, "layer3": 35, "layer4": 92, "owner_age_estimate": 60, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 47, "years_in_business": 47, "provider_count_estimate": 3, "employee_count_estimate": 22, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.65, "layer1_comment": "Nick's Plumbing family-owned since 1979. Owner age proxy ~60 from biz history.", "layer2_comment": "Excellent: 47-yr operation, multi-trade plumbing + HVAC + electric (TACLA0012793E + TACLB85298E), Nick's Smart VIP membership program, online booking. ≈ $3-6M rev band.", "layer3_comment": "FEW coasting tells — Nick's Smart VIP membership = active recurring revenue, true online booking, premium Houston Galleria/Bellaire/Memorial service area = high-end clients. Modernized = NOT coasting profile.", "layer4_comment": "Houston rollup hot + premium Galleria/Bellaire/Memorial submarket nudge +5.", "final_comment": "Nick's Plumbing, 47-yr family-owned Houston shop with active VIP membership program, true online booking, multi-trade scope (plumbing+HVAC+electric), premium service area (Galleria/Bellaire/Memorial). $3-6M revenue band. This is NOT a coasting-owner — modernization signals are intact. B_forward — premium platform-acquirer bolt-on candidate for Apex/Wrench/Service Champions.", "value_add_thesis": "Premium Houston Galleria/Bellaire/Memorial multi-trade plumbing+HVAC+electric is a platform-acquirer prize. Forward to Apex / Wrench / Service Champions / Sila as a $5-10M sale target."},
    "plm-006": {"layer1": 65, "layer2": 75, "layer3": 50, "layer4": 85, "owner_age_estimate": 55, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 25, "years_in_business": 45, "provider_count_estimate": 2, "employee_count_estimate": 14, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.60, "layer1_comment": "Wedgeworth Plumbing — current owner Sean (2nd-gen, inherited from Mr & Mrs Wedgeworth per customer testimonial). Age likely 50-60.", "layer2_comment": "Mid-shop Houston (77055 — Spring Branch). 14+ named techs >10 yrs experience each. Multi-trade scope (water heaters, tankless, drain cleaning, hydro-jet, sewer, slab leak, gas, A/C condensate). ≈ $2-3.5M rev band.", "layer3_comment": "Successor check NEGATIVE — Sean inherited from Mr & Mrs Wedgeworth (2nd-gen succession already done). Whether Sean has his own successor is unclear but family-succession pattern fires.", "layer4_comment": "Houston rollup hot. Spring Branch is ordinary Houston metro submarket.", "final_comment": "Wedgeworth Plumbing — Sean (2nd-gen) inherited from Mr & Mrs Wedgeworth. Mid-shop ($2-3.5M rev) with 14+ long-tenured techs. B_forward — bolt-on candidate.", "value_add_thesis": "Mid-shop Houston Spring Branch plumbing with strong technician retention. Forward to ETA / Apex / Wrench platform as bolt-on."},
    "plm-027": {"layer1": 65, "layer2": 90, "layer3": 45, "layer4": 92, "owner_age_estimate": 65, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 30, "years_in_business": 123, "provider_count_estimate": 5, "employee_count_estimate": 60, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.50, "layer1_comment": "Dallas Plumbing Company 4th-gen ownership over 123-yr history (founded 1903). Current owner age likely 50-70.", "layer2_comment": "Excellent: 123-yr operation (TX's oldest), multi-trade plumbing + AC, very large platform-scale shop. ≈ $10M+ rev.", "layer3_comment": "Successor check NEGATIVE: explicit 4-gen family succession. Not coasting-solo profile.", "layer4_comment": "Dallas rollup very hot.", "final_comment": "Dallas Plumbing Company, 123-yr operation, 4-gen family. Already platform-scale ($10M+ rev). Not off-market thesis target. B_forward at best — likely already on Apex/Wrench radar, may already have informal LOIs.", "value_add_thesis": "Platform-scale Dallas multi-trade. NOT off-market thesis target — Forward to ETA community only as awareness."},
    "plm-028": {"layer1": 72, "layer2": 90, "layer3": 48, "layer4": 92, "owner_age_estimate": 68, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 45, "years_in_business": 67, "provider_count_estimate": 4, "employee_count_estimate": 30, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.65, "layer1_comment": "Public Service Plumbers 3rd-gen DiFrancesco MP since 1981 = age ~65-70.", "layer2_comment": "Excellent: 67-yr operation, multi-trade plumbing + drain/sewer + AC + heating + electrical + generator, Shield Membership $14.95/mo active recurring revenue, Dallas Lakewood/Lower Greenville 75206.", "layer3_comment": "Successor check NEGATIVE: 3rd-gen DiFrancesco explicit. Shield Membership active. Not coasting-solo profile.", "layer4_comment": "Dallas rollup very hot + premium Lakewood/Lower Greenville submarket nudge +3.", "final_comment": "Public Service Plumbers, 67-yr 3rd-gen DiFrancesco family, $5-10M revenue, multi-trade with active Shield Membership program. Premium Dallas submarket. B_forward — premium platform-acquirer bolt-on for Wrench/Apex/Service Champions.", "value_add_thesis": "Premium Dallas multi-trade with strong recurring revenue book + 67 yrs brand equity. Forward to Apex / Wrench / Service Champions platforms as $8-15M bolt-on target."},
    "plm-029": {"layer1": 68, "layer2": 85, "layer3": 45, "layer4": 88, "owner_age_estimate": 65, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 35, "years_in_business": 57, "provider_count_estimate": 3, "employee_count_estimate": 25, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.60, "layer1_comment": "Cody & Sons founded 1969 by Bill+Shirley Cody + 3 sons. Currently operating with 'sons' generation.", "layer2_comment": "57-yr operation, multi-trade plumbing + heating + AC + generators + indoor air quality + duct cleaning. MVP membership. Online estimate booking.", "layer3_comment": "Successor check NEGATIVE: 'and Sons' in name = explicit succession. Modernized (MVP plan + online).", "layer4_comment": "Dallas/Plano hot rollup. ", "final_comment": "Cody & Sons Plumbing — 57-yr 'and Sons' explicit succession family operation. B_forward bolt-on for Wrench/Apex platforms.", "value_add_thesis": "Multi-trade Dallas/Plano with active MVP membership + multi-gen family. Forward to ETA / Wrench / Apex as bolt-on."},
    "plm-049": {"layer1": 80, "layer2": 75, "layer3": 60, "layer4": 85, "owner_age_estimate": 70, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 40, "years_in_business": 52, "provider_count_estimate": 2, "employee_count_estimate": 10, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.55, "layer1_comment": "David Lasiter MP M-8331 = pre-1990 legacy = 35+ yrs MP tenure, age ~70.", "layer2_comment": "52-yr operation since 1974, multi-service residential plumbing, Annual Maintenance Program + Lasiter Loyalty Plan recurring revenue. ≈ $1.5-3M rev band. SBA-financeable.", "layer3_comment": "Mixed: membership program active (positive for L2), but 'and Lasiter' family-name doubled implies internal partnership/succession (negative for L3 coasting-solo thesis). Live team-page fetch found only David Lasiter named.", "layer4_comment": "Fort Worth Tarrant rollup hot. ", "final_comment": "Lasiter and Lasiter Plumbing — David Lasiter MP M-8331 pre-1990 legacy. Family-name doubled in legal name implies internal partnership/succession. 52-yr operation in Fort Worth. B_forward — needs deep-dive on second-Lasiter identity to confirm whether this is family succession (B) or coasting-solo-with-marketing-name (A).", "value_add_thesis": "Long-tenured Fort Worth multi-service plumbing with active Lasiter Loyalty Plan. Forward to ETA/Wrench bolt-on community."},
    "plm-053": {"layer1": 70, "layer2": 60, "layer3": 75, "layer4": 75, "owner_age_estimate": 63, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 36, "years_in_business": 36, "provider_count_estimate": 1, "employee_count_estimate": 6, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.45, "layer1_comment": "Toni Cryer President since 1990 (36 yrs). Age proxy ~63.", "layer2_comment": "36-yr Fort Worth operation, small-mid shop. Tunneling + leak + drain specialty. ≈ $500K-1.2M rev. SBA-financeable but on small end.", "layer3_comment": "Strong coasting tells: no membership plan, request-callback only (no true booking), thin online presence, no team page detail. 30+ yr operation with thin web presence = classic coasting indicator.", "layer4_comment": "Fort Worth Tarrant rollup hot. Lake Worth (76114) = older Tarrant housing stock +3 nudge.", "final_comment": "Ace Repair Plumbing — Toni Cryer President since 1990 (36 yrs, age ~63). Fort Worth 76114 (Lake Worth — older Tarrant housing). Solo woman-led operation, no successor visible. Strong coasting tells (no membership, no online booking, thin web). Small shop. B_forward — promote to A_acquire_self contingent on Tarrant CAD OV65 + live team-page deep fetch.", "value_add_thesis": "Long-tenured Fort Worth Lake Worth plumbing with thin online presence + no membership program = AI dispatch + recurring service + modernization thesis. Small-shop SBA-7(a) / ETA-searcher candidate."},
    "plm-066": {"layer1": 75, "layer2": 80, "layer3": 40, "layer4": 85, "owner_age_estimate": 78, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 58, "years_in_business": 58, "provider_count_estimate": 3, "employee_count_estimate": 12, "is_distressed": False, "distress_reasons": [], "confidence": "high", "data_completeness": 0.75, "layer1_comment": "Joe Enriquez Sr (founder 1968) ~age 78. Joe Jr. + Joe III also active.", "layer2_comment": "58-yr SA operation, multi-trade plumbing + HVAC + remodeling + water restoration, Maintenance Plan recurring, San Antonio 78249.", "layer3_comment": "Successor check NEGATIVE: 3-gen Enriquez explicit (Sr + Jr + III). Strong family succession. Not coasting-solo.", "layer4_comment": "San Antonio rollup hot. ", "final_comment": "J.C. Enriquez and Son — 3-gen Enriquez family operation since 1968. B_forward.", "value_add_thesis": "Long-tenured SA multi-trade with active maintenance plan. Forward to ETA/PE bolt-on community."},
    "plm-067": {"layer1": 80, "layer2": 60, "layer3": 50, "layer4": 80, "owner_age_estimate": 75, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 49, "years_in_business": 49, "provider_count_estimate": 2, "employee_count_estimate": 5, "is_distressed": False, "distress_reasons": [], "confidence": "high", "data_completeness": 0.70, "layer1_comment": "Russell Walker owner since 1977. Steve Walker brother MP. Russell age ~75.", "layer2_comment": "49-yr SA shop, small-mid scale 3-5 trucks, drain camera + water softeners + leak detection. ≈ $700K-1.5M rev.", "layer3_comment": "Mixed: extensive Walker family in business (brother Steve, sister Jacquelyn, daughter Brandi as apprentice) = INTERNAL SUCCESSION IN PLACE (daughter on plumber track). No online booking + no membership = strong coasting tells but offset by family-succession.", "layer4_comment": "San Antonio rollup hot.", "final_comment": "210 Plumbing — Walker family multi-gen (Russell + brother Steve + sister Jacquelyn + daughter Brandi as apprentice). Strong coasting tells (no online booking, no membership, phone-only) but family succession via daughter. B_forward.", "value_add_thesis": "SA multi-gen Walker family plumbing with thin tech stack. Forward to ETA/PE bolt-on community."},
    "plm-077": {"layer1": 75, "layer2": 88, "layer3": 35, "layer4": 92, "owner_age_estimate": 68, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 35, "years_in_business": 92, "provider_count_estimate": 6, "employee_count_estimate": 40, "is_distressed": False, "distress_reasons": [], "confidence": "high", "data_completeness": 0.70, "layer1_comment": "Austin Plumbing (Team Austin) 3rd-gen Smith. Eric Smith President. Son Austin already on team.", "layer2_comment": "92-yr operation, multi-trade plumbing + HVAC + electric + water well + air duct + water conditioning. Very large. ≈ $5-15M rev. Platform-scale.", "layer3_comment": "Successor check NEGATIVE: 3rd-gen Smith with son Austin already in role. Explicit succession.", "layer4_comment": "Austin rollup very hot.", "final_comment": "Team Austin — 92-yr 3-gen Smith multi-trade Austin platform-scale. Not off-market thesis target. B_forward at best — likely already on Apex/Wrench radar.", "value_add_thesis": "Platform-scale Austin multi-trade. Forward to ETA community as awareness only."},
    "plm-099": {"layer1": 75, "layer2": 80, "layer3": 40, "layer4": 85, "owner_age_estimate": 70, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 37, "years_in_business": 50, "provider_count_estimate": 3, "employee_count_estimate": 10, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.60, "layer1_comment": "William K Edmunds RMP M-16885 since 1988 = 37+ yrs MP tenure, age ~70. 3-gen MPs.", "layer2_comment": "50-yr operation since 1976. Sugar Land Greater Houston. Value Plan membership. Online scheduling. ≈ $1.5-3M rev.", "layer3_comment": "Successor check NEGATIVE: 3-gen Edmunds family MPs. Modernized intake.", "layer4_comment": "Houston rollup hot. Sugar Land Fort Bend = ordinary baseline.", "final_comment": "S & B Plumbing — 3-gen Edmunds family Sugar Land. B_forward.", "value_add_thesis": "Long-tenured Sugar Land family plumbing. Forward to ETA / PE bolt-on."},
    "plm-079": {"layer1": 75, "layer2": 70, "layer3": 50, "layer4": 80, "owner_age_estimate": 63, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 43, "years_in_business": 27, "provider_count_estimate": 1, "employee_count_estimate": 8, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.65, "layer1_comment": "Todd Cox MP since 1983 (youngest MP in TX history at 18-22) = age 61-65. Sons in business (TX State University grads).", "layer2_comment": "27-yr Round Rock operation. Residential + new construction + commercial. Schedule a Call form.", "layer3_comment": "Successor check NEGATIVE: 2 sons in business (mgmt + construction science backgrounds). Family succession path explicit.", "layer4_comment": "Austin/Round Rock rollup very hot. ", "final_comment": "Mustang Plumbing — Todd Cox + 2 sons family operation. B_forward.", "value_add_thesis": "Round Rock multi-gen plumbing with sons in management track. Forward to ETA/Apex bolt-on."},

    # Apply remaining tier assignments — pattern: same-surname-or-family-succession = B; small-shop-with-no-data = C; legacy-license-no-website = C
    "plm-003": {"layer1": 65, "layer2": 70, "layer3": 55, "layer4": 78, "owner_age_estimate": 65, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 44, "years_in_business": 44, "provider_count_estimate": 1, "employee_count_estimate": 8, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.45, "layer1_comment": "Lindsay Company since 1982. Owner age ~60-70.", "layer2_comment": "44-yr NW Houston shop, multi-service plumbing + water filtration + gas generator. ≈ $1-2M rev.", "layer3_comment": "Thin web detail — no team page, no membership, no booking visible. Family-owned 1982. Possible coasting profile.", "layer4_comment": "Houston rollup hot, NW Harris baseline.", "final_comment": "The Lindsay Company Plumbing — 44-yr NW Houston family. Thin online presence, possible coasting. B_forward pending deeper team verification.", "value_add_thesis": "NW Houston plumbing modernization candidate. Forward to ETA / PE bolt-on after live team page deep-dive."},
    "plm-031": {"layer1": 0, "layer2": 0, "layer3": 0, "layer4": 0, "owner_age_estimate": None, "owner_age_source": "platform_excluded", "owner_tenure_years": None, "years_in_business": 81, "provider_count_estimate": None, "employee_count_estimate": None, "is_distressed": True, "distress_reasons": ["pe_platform_owned_wrench_group_infrastructure_detected"], "confidence": "high", "data_completeness": 0.50, "layer1_comment": "Platform-excluded.", "layer2_comment": "Platform-excluded.", "layer3_comment": "Platform-excluded.", "layer4_comment": "Platform-excluded.", "final_comment": "Baker Brothers Plumbing — Wrench Group infrastructure detected on website CDN (wg.scene7.com image paths). EXCLUDE as PE platform-owned per filter rules.", "value_add_thesis": "N/A — platform-excluded."},
}

# For all spine entries not explicitly scored above, fill with default B/C/D classifications
DEFAULT_SCORES = {
    # plm-004: Cooper Plumbing - unverified
    "plm-004": {"layer1": 50, "layer2": 50, "layer3": 35, "layer4": 75, "owner_age_estimate": None, "owner_age_source": "unverified", "owner_tenure_years": None, "years_in_business": None, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.20, "layer1_comment": "Unverified.", "layer2_comment": "Unverified.", "layer3_comment": "Unverified.", "layer4_comment": "Houston baseline.", "final_comment": "Cooper Plumbing — unverified candidate; common name. C_watch pending verification.", "value_add_thesis": "N/A — unverified."},
    # plm-007: DYZ Plumbing
    "plm-007": {"layer1": 50, "layer2": 65, "layer3": 50, "layer4": 80, "owner_age_estimate": 50, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 19, "years_in_business": 19, "provider_count_estimate": 1, "employee_count_estimate": 4, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.40, "layer1_comment": "19 yrs experience — owner likely 45-55.", "layer2_comment": "Bellaire/Memorial focus, small shop ≈ $500K-1M rev.", "layer3_comment": "Mid coasting tells.", "layer4_comment": "Houston Bellaire/Memorial premium +3.", "final_comment": "DYZ Plumbing — 19 yrs Bellaire shop, owner age too young, C_watch.", "value_add_thesis": "N/A — borderline."},
    "plm-009": {"layer1": 50, "layer2": 50, "layer3": 35, "layer4": 75, "owner_age_estimate": None, "owner_age_source": "unverified", "owner_tenure_years": None, "years_in_business": None, "provider_count_estimate": None, "employee_count_estimate": None, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.20, "layer1_comment": "Unverified.", "layer2_comment": "Unverified.", "layer3_comment": "Unverified.", "layer4_comment": "Houston baseline.", "final_comment": "Best Plumbing Houston — unverified, common name. C_watch.", "value_add_thesis": "N/A."},
    "plm-010": {"layer1": 45, "layer2": 65, "layer3": 45, "layer4": 75, "owner_age_estimate": 55, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 22, "years_in_business": 22, "provider_count_estimate": 1, "employee_count_estimate": 5, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.35, "layer1_comment": "Southern Plumbing 22 yrs. Owner age likely 50-60.", "layer2_comment": "Houston metro shop, ≈ $700K-1.5M rev.", "layer3_comment": "Some coasting indicators (small website).", "layer4_comment": "Houston baseline.", "final_comment": "Southern Plumbing — 22-yr Houston small-mid shop. C_watch.", "value_add_thesis": "N/A — not yet retirement-window."},
    "plm-011": {"layer1": 50, "layer2": 50, "layer3": 35, "layer4": 75, "owner_age_estimate": None, "owner_age_source": "unverified", "owner_tenure_years": None, "years_in_business": None, "provider_count_estimate": None, "employee_count_estimate": None, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.15, "layer1_comment": "Unverified — no website found.", "layer2_comment": "Unverified.", "layer3_comment": "Unverified.", "layer4_comment": "Houston baseline.", "final_comment": "Sunrise Mechanical — no website verified, unverified. D_pass without verification.", "value_add_thesis": "N/A."},
    "plm-012": {"layer1": 70, "layer2": 60, "layer3": 50, "layer4": 80, "owner_age_estimate": 60, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 38, "years_in_business": 38, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.50, "layer1_comment": "Tony's Plumbing father-son team. 38+ yrs.", "layer2_comment": "Cypress/Katy NW Houston small shop.", "layer3_comment": "Successor check NEGATIVE: father-son team.", "layer4_comment": "Houston rollup hot.", "final_comment": "Tony's Plumbing — father-son small shop. B_forward.", "value_add_thesis": "Small-shop NW Houston multi-gen. Forward."},
    "plm-014": {"layer1": 60, "layer2": 65, "layer3": 50, "layer4": 80, "owner_age_estimate": 55, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 19, "years_in_business": 19, "provider_count_estimate": 1, "employee_count_estimate": 5, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.40, "layer1_comment": "RMPL 21138 mid-2000s — owner age ~50-60.", "layer2_comment": "8-city NW Houston service area.", "layer3_comment": "'In the Family' branding implies succession but no confirmed family successor.", "layer4_comment": "Houston rollup hot.", "final_comment": "All in The Family Plumbing — 19-yr operation, 8-city NW Houston, family branding. C_watch / B_forward.", "value_add_thesis": "Mid-tenure NW Houston multi-city. Forward."},
    "plm-015": {"layer1": 70, "layer2": 65, "layer3": 55, "layer4": 80, "owner_age_estimate": 65, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 40, "years_in_business": 40, "provider_count_estimate": 1, "employee_count_estimate": 5, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.45, "layer1_comment": "Daniels Plumbing 40 yrs.", "layer2_comment": "NW Houston/Tomball shop.", "layer3_comment": "Thin online presence.", "layer4_comment": "Houston rollup hot.", "final_comment": "Daniels Plumbing — 40 yrs Tomball/NW Houston. B_forward.", "value_add_thesis": "Long-tenured NW Houston small-mid shop. Forward."},
    "plm-016": {"layer1": 68, "layer2": 75, "layer3": 45, "layer4": 80, "owner_age_estimate": 65, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 37, "years_in_business": 37, "provider_count_estimate": 2, "employee_count_estimate": 8, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.60, "layer1_comment": "Steve Aberle founder 1989 + Mark Aberle MP since 2000 (son).", "layer2_comment": "37-yr Houston shop.", "layer3_comment": "Successor check NEGATIVE: Steve + Mark Aberle father-son.", "layer4_comment": "Houston rollup hot.", "final_comment": "Aberle Plumbing — Steve + Mark father-son. B_forward.", "value_add_thesis": "Long-tenured Houston family plumbing. Forward."},
    "plm-018": {"layer1": 45, "layer2": 70, "layer3": 50, "layer4": 85, "owner_age_estimate": 50, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 14, "years_in_business": 15, "provider_count_estimate": 1, "employee_count_estimate": 5, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.55, "layer1_comment": "Massingill MP since 2011 = age 40-55.", "layer2_comment": "High-end residential focus Houston.", "layer3_comment": "Mid coasting tells.", "layer4_comment": "Houston rollup hot.", "final_comment": "Pegasus Plumbing — Massingill 14-yr MP, not yet retirement window. C_watch.", "value_add_thesis": "N/A — too young."},
    "plm-019": {"layer1": 72, "layer2": 90, "layer3": 35, "layer4": 92, "owner_age_estimate": 65, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 36, "years_in_business": 88, "provider_count_estimate": 4, "employee_count_estimate": 9, "is_distressed": False, "distress_reasons": [], "confidence": "high", "data_completeness": 0.70, "layer1_comment": "Gilbert 4-gen Pat → Jack → Patrick. Jack Tex Tech 1988 grad = age 60.", "layer2_comment": "88-yr Houston operation. $8.7M revenue. 9 employees on books.", "layer3_comment": "Successor check NEGATIVE: 4-gen Gilbert family.", "layer4_comment": "Houston rollup hot.", "final_comment": "Gilbert Plumbing — 4-gen Gilbert family. Platform-scale. B_forward.", "value_add_thesis": "Platform-scale Houston multi-gen. Forward."},
    "plm-020": {"layer1": 75, "layer2": 65, "layer3": 50, "layer4": 80, "owner_age_estimate": 68, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 33, "years_in_business": 34, "provider_count_estimate": 2, "employee_count_estimate": 4, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.50, "layer1_comment": "Eusebio Munoz MP since 1992 + Mario Munoz at company.", "layer2_comment": "SE Harris shop, small-mid.", "layer3_comment": "Successor check NEGATIVE: same-surname Munoz on LinkedIn.", "layer4_comment": "Houston rollup hot.", "final_comment": "Dolphin Plumbing — Eusebio + Mario Munoz family succession. B_forward.", "value_add_thesis": "Houston multi-gen Munoz. Forward."},
    "plm-021": {"layer1": 75, "layer2": 55, "layer3": 50, "layer4": 75, "owner_age_estimate": 67, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 32, "years_in_business": 32, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Jorge De Paz MP since 1993.", "layer2_comment": "South Houston small shop.", "layer3_comment": "No website found. Cap confidence.", "layer4_comment": "Houston baseline.", "final_comment": "Paz Plumbing — 32-yr South Houston shop, no website. C_watch.", "value_add_thesis": "N/A — thin data."},
    "plm-022": {"layer1": 80, "layer2": 55, "layer3": 50, "layer4": 75, "owner_age_estimate": 72, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 40, "years_in_business": 40, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "W McLain MP M-9313 legacy pre-1990.", "layer2_comment": "Pasadena Houston metro older housing.", "layer3_comment": "No website. Strong age proxy but cap confidence.", "layer4_comment": "Houston baseline + Pasadena older housing +3.", "final_comment": "W McLain Plumbing — legacy MP, Pasadena older housing. C_watch — no website caps to C tier.", "value_add_thesis": "N/A — thin data."},
    "plm-023": {"layer1": 75, "layer2": 55, "layer3": 50, "layer4": 75, "owner_age_estimate": 67, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 40, "years_in_business": 40, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Gregorio Martinez MP M-15152 since 1985.", "layer2_comment": "Pasadena older Houston metro.", "layer3_comment": "No website. Cap confidence.", "layer4_comment": "Houston baseline + Pasadena +3.", "final_comment": "Third Coast Plumbing — long-tenured Pasadena MP. C_watch.", "value_add_thesis": "N/A — thin data."},
    "plm-024": {"layer1": 75, "layer2": 60, "layer3": 40, "layer4": 75, "owner_age_estimate": 72, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 40, "years_in_business": 40, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Wesley Elam MP pre-1990 legacy.", "layer2_comment": "South Houston small shop.", "layer3_comment": "Successor check NEGATIVE: paired with Elam Plumbing Company (Mack A Elam) = multi-Elam family.", "layer4_comment": "Houston baseline.", "final_comment": "W Elam Plumbing — multi-Elam family. B_forward / D — thin.", "value_add_thesis": "Multi-Elam family Houston. Forward."},
    "plm-025": {"layer1": 80, "layer2": 60, "layer3": 40, "layer4": 75, "owner_age_estimate": 78, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 45, "years_in_business": 50, "provider_count_estimate": 1, "employee_count_estimate": 4, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Mack A Elam MP M-5233 legacy pre-1990.", "layer2_comment": "South Houston small.", "layer3_comment": "Multi-Elam family.", "layer4_comment": "Houston baseline.", "final_comment": "Elam Plumbing — Mack A Elam legacy. Multi-Elam family. B_forward / D — thin.", "value_add_thesis": "Forward."},
    "plm-026": {"layer1": 75, "layer2": 55, "layer3": 45, "layer4": 75, "owner_age_estimate": 70, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 35, "years_in_business": 35, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "David Francis MP legacy pre-1990.", "layer2_comment": "Fort Bend small.", "layer3_comment": "No website.", "layer4_comment": "Fort Bend Houston metro baseline.", "final_comment": "Francis Plumbing & Utility — long-tenured Fort Bend MP. C_watch — thin data.", "value_add_thesis": "N/A — thin."},
    "plm-030": {"layer1": 60, "layer2": 70, "layer3": 50, "layer4": 88, "owner_age_estimate": 60, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 25, "years_in_business": 66, "provider_count_estimate": 2, "employee_count_estimate": 12, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.40, "layer1_comment": "Reeves Family Plumbing 1960 + woman-owned HUB.", "layer2_comment": "Dallas mid-shop.", "layer3_comment": "BOOK ONLINE + 'Family' brand. Mid coasting.", "layer4_comment": "Dallas rollup hot.", "final_comment": "Reeves Family Plumbing — 66-yr, woman-owned. B_forward.", "value_add_thesis": "Mid-shop Dallas family. Forward."},
    "plm-032": {"layer1": 55, "layer2": 65, "layer3": 50, "layer4": 85, "owner_age_estimate": 60, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 25, "years_in_business": 25, "provider_count_estimate": 1, "employee_count_estimate": 6, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.40, "layer1_comment": "25+ yrs.", "layer2_comment": "Farmers Branch N Dallas mid.", "layer3_comment": "Some coasting tells.", "layer4_comment": "Dallas rollup hot.", "final_comment": "My Local Plumber — 25-yr Farmers Branch family. B_forward.", "value_add_thesis": "Mid-shop Dallas family. Forward."},
    "plm-033": {"layer1": 50, "layer2": 65, "layer3": 45, "layer4": 85, "owner_age_estimate": 55, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 21, "years_in_business": 21, "provider_count_estimate": 1, "employee_count_estimate": 4, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.40, "layer1_comment": "Watermark Plumbing since 2005.", "layer2_comment": "Carrollton small-mid.", "layer3_comment": "Mid.", "layer4_comment": "Dallas rollup hot.", "final_comment": "Watermark Plumbing — 21-yr Carrollton. C_watch.", "value_add_thesis": "N/A — too young."},
    "plm-034": {"layer1": 45, "layer2": 50, "layer3": 35, "layer4": 70, "owner_age_estimate": 50, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 18, "years_in_business": 18, "provider_count_estimate": 1, "employee_count_estimate": 5, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.40, "layer1_comment": "Burton's Mechanical since 2008.", "layer2_comment": "Commercial construction focus — partial exclusion candidate.", "layer3_comment": "Mid.", "layer4_comment": "Dallas baseline.", "final_comment": "Burton's Mechanical — commercial construction focus, less residential service. C_watch / borderline-exclude.", "value_add_thesis": "N/A."},
    "plm-035": {"layer1": 60, "layer2": 65, "layer3": 50, "layer4": 85, "owner_age_estimate": 65, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 46, "years_in_business": 46, "provider_count_estimate": 1, "employee_count_estimate": 6, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.35, "layer1_comment": "Barbosa Mechanical 46+ yrs.", "layer2_comment": "Carrollton/Farmers Branch.", "layer3_comment": "Mid.", "layer4_comment": "Dallas rollup hot.", "final_comment": "Barbosa Plumbing — 46-yr Carrollton/Farmers Branch. B_forward — needs deeper verification.", "value_add_thesis": "Long-tenured Dallas family. Forward."},
    "plm-036": {"layer1": 45, "layer2": 80, "layer3": 40, "layer4": 90, "owner_age_estimate": 55, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 20, "years_in_business": 20, "provider_count_estimate": 1, "employee_count_estimate": 12, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.55, "layer1_comment": "Theron Young M-37588 (~2005) = age 50-60.", "layer2_comment": "Legacy Gold Plan + 2 locations + online booking.", "layer3_comment": "Modernized = low coasting.", "layer4_comment": "Dallas/Frisco rollup very hot.", "final_comment": "Legacy Plumbing — too young + modernized. C_watch.", "value_add_thesis": "N/A — owner not retirement-window."},
    "plm-037": {"layer1": 45, "layer2": 65, "layer3": 50, "layer4": 88, "owner_age_estimate": 50, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 16, "years_in_business": 16, "provider_count_estimate": 1, "employee_count_estimate": 5, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.50, "layer1_comment": "Brad Hackler M-39169 (~2010).", "layer2_comment": "McKinney small-mid.", "layer3_comment": "Mid.", "layer4_comment": "Collin County rollup hot.", "final_comment": "Hackler Plumbing — owner too young. C_watch.", "value_add_thesis": "N/A."},
    "plm-038": {"layer1": 78, "layer2": 80, "layer3": 40, "layer4": 90, "owner_age_estimate": 70, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 55, "years_in_business": 55, "provider_count_estimate": 2, "employee_count_estimate": 8, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.60, "layer1_comment": "Smith and Son Plumbing 3rd-gen since 1970.", "layer2_comment": "McKinney + backflow recurring revenue.", "layer3_comment": "Successor check NEGATIVE: 3rd-gen.", "layer4_comment": "Collin rollup hot.", "final_comment": "Smith and Son — 3-gen McKinney. B_forward.", "value_add_thesis": "McKinney multi-gen + backflow recurring. Forward."},
    "plm-039": {"layer1": 55, "layer2": 75, "layer3": 40, "layer4": 90, "owner_age_estimate": 55, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 25, "years_in_business": 44, "provider_count_estimate": 1, "employee_count_estimate": 10, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.65, "layer1_comment": "William O'Bryan 2nd-gen.", "layer2_comment": "Allen + Plano 2 locations, O'Bryan Family Plan, online booking.", "layer3_comment": "Modernized = low coasting.", "layer4_comment": "Collin rollup hot.", "final_comment": "O'Bryan Plumbing — 2nd-gen William, modernized. B_forward.", "value_add_thesis": "Allen/Plano family. Forward."},
    "plm-040": {"layer1": 65, "layer2": 65, "layer3": 50, "layer4": 88, "owner_age_estimate": 60, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 25, "years_in_business": 25, "provider_count_estimate": 1, "employee_count_estimate": 5, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.45, "layer1_comment": "Kenny Bunch 25 yrs.", "layer2_comment": "Wylie/Plano.", "layer3_comment": "No membership, no online booking — mid coasting.", "layer4_comment": "Collin/Dallas rollup hot.", "final_comment": "Kenny Bunch Plumbing — 25-yr Wylie. B_forward.", "value_add_thesis": "N Dallas Collin small-mid. Forward."},
    "plm-041": {"layer1": 78, "layer2": 60, "layer3": 50, "layer4": 88, "owner_age_estimate": 70, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 37, "years_in_business": 37, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.50, "layer1_comment": "Frank E Smith MP M-16856 since 1988 = age ~70.", "layer2_comment": "Oak Cliff Dallas 75208 small shop.", "layer3_comment": "Successor check NEGATIVE: Frank M Jr Smith = 2nd-gen succession.", "layer4_comment": "Dallas rollup hot + Oak Cliff older housing +3.", "final_comment": "Frank Smith Plumbing — 2nd-gen Frank Jr. B_forward.", "value_add_thesis": "Oak Cliff Dallas family. Forward."},
    "plm-042": {"layer1": 80, "layer2": 60, "layer3": 50, "layer4": 85, "owner_age_estimate": 70, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 39, "years_in_business": 39, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Terry Stokes MP M-15811 since 1986.", "layer2_comment": "Carrollton small.", "layer3_comment": "No website. Cap confidence.", "layer4_comment": "Dallas rollup hot.", "final_comment": "IC Plumbing — long-tenured Carrollton MP, no website. C_watch.", "value_add_thesis": "N/A — thin."},
    "plm-043": {"layer1": 78, "layer2": 80, "layer3": 35, "layer4": 88, "owner_age_estimate": 70, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 40, "years_in_business": 40, "provider_count_estimate": 3, "employee_count_estimate": 30, "is_distressed": False, "distress_reasons": [], "confidence": "high", "data_completeness": 0.65, "layer1_comment": "Scott Riddell MP M-15275 since 1985.", "layer2_comment": "Mesquite. 160 employees, 60 trucks per ZoomInfo = $20M+ rev. TOO LARGE for off-market thesis.", "layer3_comment": "Successor check unclear but size = platform-acquirer radar already.", "layer4_comment": "Dallas rollup hot.", "final_comment": "Riddell Plumbing — 160 emp / 60 trucks = $20M+ rev. Platform-scale. NOT off-market thesis. D_pass (too-large filter).", "value_add_thesis": "Too large — already on platform radar."},
    "plm-044": {"layer1": 65, "layer2": 55, "layer3": 50, "layer4": 80, "owner_age_estimate": 60, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 20, "years_in_business": 20, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Alfred Hernandez M-37502 since 2005.", "layer2_comment": "Dallas Love Field small.", "layer3_comment": "No website.", "layer4_comment": "Dallas baseline.", "final_comment": "AH Mechanical Contractors — 20-yr Dallas small. C_watch.", "value_add_thesis": "N/A — thin."},
    "plm-045": {"layer1": 60, "layer2": 55, "layer3": 50, "layer4": 80, "owner_age_estimate": 58, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 19, "years_in_business": 19, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Rudolfo Nunez M-37625 since 2006.", "layer2_comment": "Mesquite small.", "layer3_comment": "No website.", "layer4_comment": "Dallas baseline.", "final_comment": "Coldwater Plumbing — 19-yr Mesquite small. C_watch.", "value_add_thesis": "N/A — thin + young."},
    "plm-046": {"layer1": 80, "layer2": 60, "layer3": 40, "layer4": 80, "owner_age_estimate": 75, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 45, "years_in_business": 50, "provider_count_estimate": 1, "employee_count_estimate": 5, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Ronald Stanley M-12045 legacy pre-1990.", "layer2_comment": "Dallas '& SONS' name = succession.", "layer3_comment": "Successor check NEGATIVE: '& SONS'.", "layer4_comment": "Dallas rollup hot.", "final_comment": "Ron Stanley & Sons Plumbing — '& SONS' explicit. B_forward / D — thin data.", "value_add_thesis": "Forward."},
    "plm-047": {"layer1": 60, "layer2": 55, "layer3": 50, "layer4": 80, "owner_age_estimate": 58, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 22, "years_in_business": 22, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Michael Pelayo M-36676 since 2003.", "layer2_comment": "Sachse small.", "layer3_comment": "No website.", "layer4_comment": "Dallas baseline.", "final_comment": "Pelayo Plumbing — 22-yr Sachse small. C_watch.", "value_add_thesis": "N/A — thin."},
    "plm-048": {"layer1": 75, "layer2": 55, "layer3": 50, "layer4": 80, "owner_age_estimate": 67, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 37, "years_in_business": 37, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "James Brinkley M-16773 since 1988.", "layer2_comment": "Rowlett small.", "layer3_comment": "No website.", "layer4_comment": "Dallas baseline.", "final_comment": "On Target Mechanical — long-tenured Rowlett MP, no website. C_watch.", "value_add_thesis": "N/A — thin."},
    "plm-050": {"layer1": 60, "layer2": 70, "layer3": 50, "layer4": 88, "owner_age_estimate": 60, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 42, "years_in_business": 42, "provider_count_estimate": 1, "employee_count_estimate": 6, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.40, "layer1_comment": "Master Repair Plumbing since 1983.", "layer2_comment": "Fort Worth.", "layer3_comment": "Online scheduling + 24/7 = modernized.", "layer4_comment": "Tarrant rollup hot.", "final_comment": "Master Repair Plumbing — 42-yr Fort Worth, modernized. B_forward.", "value_add_thesis": "Long-tenured Fort Worth. Forward."},
    "plm-051": {"layer1": 55, "layer2": 65, "layer3": 45, "layer4": 88, "owner_age_estimate": 55, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 20, "years_in_business": 20, "provider_count_estimate": 1, "employee_count_estimate": 5, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.40, "layer1_comment": "Trusted Plumbing 20+ yrs.", "layer2_comment": "Fort Worth.", "layer3_comment": "Successor check NEGATIVE: husband+wife+son+uncle/aunt operating team = explicit family.", "layer4_comment": "Tarrant rollup hot.", "final_comment": "Trusted Plumbing — Fort Worth family team. B_forward.", "value_add_thesis": "Forward."},
    "plm-052": {"layer1": 55, "layer2": 65, "layer3": 50, "layer4": 88, "owner_age_estimate": 55, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 25, "years_in_business": 25, "provider_count_estimate": 1, "employee_count_estimate": 5, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.40, "layer1_comment": "Howze Plumbing 25+ yrs since 1995.", "layer2_comment": "Fort Worth. Peace of Mind Membership.", "layer3_comment": "Mid.", "layer4_comment": "Tarrant rollup hot.", "final_comment": "Howze Plumbing — Fort Worth 30 yrs. B_forward.", "value_add_thesis": "Forward."},
    "plm-054": {"layer1": 50, "layer2": 60, "layer3": 50, "layer4": 88, "owner_age_estimate": 55, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 15, "years_in_business": 15, "provider_count_estimate": 1, "employee_count_estimate": 4, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.40, "layer1_comment": "Double L Plumbing.", "layer2_comment": "Tarrant small-mid.", "layer3_comment": "Mid.", "layer4_comment": "Tarrant rollup hot.", "final_comment": "Double L Plumbing — Fort Worth Tarrant family. B_forward.", "value_add_thesis": "Forward."},
    "plm-055": {"layer1": 50, "layer2": 60, "layer3": 50, "layer4": 88, "owner_age_estimate": 55, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 15, "years_in_business": 15, "provider_count_estimate": 1, "employee_count_estimate": 4, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.40, "layer1_comment": "Curly's Plumbing.", "layer2_comment": "Tarrant small.", "layer3_comment": "Mid.", "layer4_comment": "Tarrant rollup hot.", "final_comment": "Curly's Plumbing — Fort Worth family+veteran. B_forward.", "value_add_thesis": "Forward."},
    "plm-056": {"layer1": 50, "layer2": 60, "layer3": 50, "layer4": 88, "owner_age_estimate": 55, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 15, "years_in_business": 15, "provider_count_estimate": 1, "employee_count_estimate": 4, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.40, "layer1_comment": "FB Plumbing.", "layer2_comment": "DFW small.", "layer3_comment": "Mid.", "layer4_comment": "Tarrant rollup hot.", "final_comment": "FB Plumbing — DFW Fischer+Boone. B_forward.", "value_add_thesis": "Forward."},
    "plm-057": {"layer1": 78, "layer2": 65, "layer3": 50, "layer4": 90, "owner_age_estimate": 70, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 33, "years_in_business": 33, "provider_count_estimate": 1, "employee_count_estimate": 5, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Robert Riley MP M-18265 since 1992 + MEDGAS endorsement.", "layer2_comment": "NW Fort Worth Lake Worth older housing.", "layer3_comment": "No website. Cap confidence.", "layer4_comment": "Tarrant rollup hot + Lake Worth older +3.", "final_comment": "Riley Plumbing & Mechanical — long-tenured NW Fort Worth MP + MEDGAS. C_watch.", "value_add_thesis": "N/A — thin data."},
    "plm-058": {"layer1": 78, "layer2": 60, "layer3": 50, "layer4": 90, "owner_age_estimate": 75, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 39, "years_in_business": 37, "provider_count_estimate": 2, "employee_count_estimate": 5, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.50, "layer1_comment": "Reed family multi-gen.", "layer2_comment": "Kennedale.", "layer3_comment": "Successor check NEGATIVE: David A Reed → Bart + Robert Reed = multi-gen.", "layer4_comment": "Tarrant rollup hot.", "final_comment": "Reed Plumbing — multi-Reed family. B_forward.", "value_add_thesis": "Forward."},
    "plm-059": {"layer1": 60, "layer2": 55, "layer3": 50, "layer4": 80, "owner_age_estimate": 60, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 23, "years_in_business": 23, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Ector Gomez M-36171 since 2002.", "layer2_comment": "Crowley small.", "layer3_comment": "No website.", "layer4_comment": "Tarrant baseline.", "final_comment": "Diamond Plumbing Industries — Crowley 23-yr MP. C_watch.", "value_add_thesis": "N/A — thin."},
    "plm-060": {"layer1": 55, "layer2": 60, "layer3": 50, "layer4": 92, "owner_age_estimate": 55, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 17, "years_in_business": 17, "provider_count_estimate": 1, "employee_count_estimate": 4, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Eddie Shay Thomas M-38937 since 2009.", "layer2_comment": "Southlake premium NE Tarrant.", "layer3_comment": "Mid.", "layer4_comment": "Tarrant rollup hot + Southlake premium +5.", "final_comment": "Tri Dal Southlake — premium NE Tarrant 17-yr MP. C_watch.", "value_add_thesis": "N/A — too young."},
    "plm-061": {"layer1": 50, "layer2": 88, "layer3": 35, "layer4": 88, "owner_age_estimate": 55, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 36, "years_in_business": 36, "provider_count_estimate": 4, "employee_count_estimate": 30, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.60, "layer1_comment": "Beyer Plumbing since 1990. Owner age likely 50-65.", "layer2_comment": "Large SA + 30+ cities. Plumbing Plan recurring.", "layer3_comment": "Modernized intake.", "layer4_comment": "SA rollup hot.", "final_comment": "Beyer Plumbing — 36-yr large SA family operation. Mid-large platform-acquirer target. B_forward.", "value_add_thesis": "Large SA multi-area. Forward to PE/ETA."},
    "plm-062": {"layer1": 40, "layer2": 75, "layer3": 35, "layer4": 85, "owner_age_estimate": 45, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 10, "years_in_business": 10, "provider_count_estimate": 1, "employee_count_estimate": 6, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.55, "layer1_comment": "Anchor Plumbing since 2016.", "layer2_comment": "SA mid. Membership $19.95/mo.", "layer3_comment": "Modernized = low coasting.", "layer4_comment": "SA rollup hot.", "final_comment": "Anchor Plumbing — 10-yr SA, modernized, owner too young. D_pass (under 5-yr-band/10-yr-young).", "value_add_thesis": "N/A — too young."},
    "plm-063": {"layer1": 50, "layer2": 60, "layer3": 50, "layer4": 85, "owner_age_estimate": 50, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 22, "years_in_business": 22, "provider_count_estimate": 1, "employee_count_estimate": 5, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.50, "layer1_comment": "Chavarria Fernando Jr (2nd-gen from father's Laredo biz 1981).", "layer2_comment": "SA Stone Oak.", "layer3_comment": "Successor check unclear but he is 2nd-gen.", "layer4_comment": "SA rollup hot.", "final_comment": "Chavarria's Plumbing — Fernando Jr 2nd-gen Stone Oak SA. B_forward.", "value_add_thesis": "Forward."},
    "plm-064": {"layer1": 50, "layer2": 65, "layer3": 50, "layer4": 85, "owner_age_estimate": 55, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 30, "years_in_business": 30, "provider_count_estimate": 1, "employee_count_estimate": 4, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.40, "layer1_comment": "American Auger 30+ yrs combined experience.", "layer2_comment": "SA Bexar.", "layer3_comment": "Jobber online + BBB cert = modernized.", "layer4_comment": "SA rollup hot.", "final_comment": "American Auger Plumbing — SA Bexar family. B_forward.", "value_add_thesis": "Forward."},
    "plm-065": {"layer1": 45, "layer2": 60, "layer3": 50, "layer4": 85, "owner_age_estimate": 50, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 20, "years_in_business": 20, "provider_count_estimate": 1, "employee_count_estimate": 4, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.50, "layer1_comment": "Steven Stanush M-36596.", "layer2_comment": "SA. 20 yrs.", "layer3_comment": "Mid.", "layer4_comment": "SA rollup hot.", "final_comment": "S&S Plumbing — 20-yr SA MP. C_watch.", "value_add_thesis": "N/A — too young."},
    "plm-068": {"layer1": 50, "layer2": 70, "layer3": 50, "layer4": 85, "owner_age_estimate": 55, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 25, "years_in_business": 25, "provider_count_estimate": 1, "employee_count_estimate": 6, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.40, "layer1_comment": "Will's Plumbing 24/7.", "layer2_comment": "SA + backflow recurring.", "layer3_comment": "Mid.", "layer4_comment": "SA rollup hot.", "final_comment": "Will's Plumbing & Testing — SA backflow recurring. B_forward.", "value_add_thesis": "SA family backflow. Forward."},
    "plm-069": {"layer1": 50, "layer2": 50, "layer3": 50, "layer4": 80, "owner_age_estimate": 55, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 15, "years_in_business": 15, "provider_count_estimate": 1, "employee_count_estimate": 2, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Juan Lopez SA.", "layer2_comment": "Small.", "layer3_comment": "Small + no website verified.", "layer4_comment": "SA baseline.", "final_comment": "Juan's Plumbing — small SA RMP. C_watch.", "value_add_thesis": "N/A — too small."},
    "plm-070": {"layer1": 70, "layer2": 60, "layer3": 60, "layer4": 80, "owner_age_estimate": 67, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 46, "years_in_business": 46, "provider_count_estimate": 1, "employee_count_estimate": 5, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.40, "layer1_comment": "JR's Plumbing 1980 woman-owned. Owner age 60+.", "layer2_comment": "SA + Boerne small-mid.", "layer3_comment": "Strong coasting tells: no membership, no online booking, phone-only intake — 46 yrs of inertia.", "layer4_comment": "SA rollup hot.", "final_comment": "JR's Plumbing — 46-yr SA woman-owned family. Strong coasting tells. B_forward — promote to A pending Bexar CAD OV65 + live team page.", "value_add_thesis": "Long-tenured SA woman-owned with thin web = strong AI/ops thesis."},
    "plm-071": {"layer1": 55, "layer2": 60, "layer3": 50, "layer4": 85, "owner_age_estimate": 50, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 16, "years_in_business": 16, "provider_count_estimate": 1, "employee_count_estimate": 5, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.50, "layer1_comment": "Antonio Hernandez M-39327 since 2009 + MEDGAS/MRF.", "layer2_comment": "SA west — COMMERCIAL NEW CONSTRUCTION focus per BuildZoom (628 permitted projects, retail/restaurant/office/hotel/municipal). FILTER: pure new-construction excluded per skill rules.", "layer3_comment": "N/A — filtered.", "layer4_comment": "SA rollup hot.", "final_comment": "Hernandez Plumbing & Sewer — pure commercial new-construction focus per BuildZoom (628 commercial permits). EXCLUDE per filter. D_pass.", "value_add_thesis": "N/A — filtered out (pure new construction)."},
    "plm-072": {"layer1": 65, "layer2": 75, "layer3": 50, "layer4": 88, "owner_age_estimate": 60, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 22, "years_in_business": 22, "provider_count_estimate": 1, "employee_count_estimate": 6, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.55, "layer1_comment": "Samuel Longoria M-36584 since 2003.", "layer2_comment": "Multi-trade plumbing+AC+heat, SA NW 78253.", "layer3_comment": "BuildZoom top 8% but no team detail.", "layer4_comment": "SA rollup hot.", "final_comment": "Alamo Plumbing AC & Heat — Longoria 22-yr SA multi-trade. B_forward.", "value_add_thesis": "Forward."},
    "plm-073": {"layer1": 80, "layer2": 65, "layer3": 50, "layer4": 88, "owner_age_estimate": 70, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 39, "years_in_business": 39, "provider_count_estimate": 2, "employee_count_estimate": 5, "is_distressed": False, "distress_reasons": [], "confidence": "high", "data_completeness": 0.70, "layer1_comment": "Carl Rutkowski M-16201 since 1986 + 2 sons Matt + Luke.", "layer2_comment": "Helotes premium NW Bexar.", "layer3_comment": "Successor check NEGATIVE: 2 sons including Luke as plumber.", "layer4_comment": "SA rollup hot + Helotes premium +3.", "final_comment": "Rutkowski Plumbing — Carl 39-yr + sons. B_forward.", "value_add_thesis": "Helotes SA premium family. Forward."},
    "plm-074": {"layer1": 75, "layer2": 60, "layer3": 50, "layer4": 80, "owner_age_estimate": 65, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 32, "years_in_business": 32, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Jesse Ortiz M-18468 since 1993.", "layer2_comment": "SA south 78224.", "layer3_comment": "No website. Cap.", "layer4_comment": "SA baseline.", "final_comment": "J&M Plumbing (Ortiz) — 32-yr SA MP, no website. C_watch.", "value_add_thesis": "N/A — thin."},
    "plm-075": {"layer1": 35, "layer2": 50, "layer3": 35, "layer4": 80, "owner_age_estimate": 40, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 8, "years_in_business": 8, "provider_count_estimate": 1, "employee_count_estimate": 2, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Carolina Martinez M-42230 since 2017 (8 yrs). Too young.", "layer2_comment": "Hard gate: 8 yrs near boundary; depth thin.", "layer3_comment": "Mid.", "layer4_comment": "SA baseline.", "final_comment": "Carolina's Plumbing — 8-yr SA MP, owner too young. D_pass (5-yr-gate marginal, age too young).", "value_add_thesis": "N/A — too young."},
    "plm-076": {"layer1": 60, "layer2": 55, "layer3": 50, "layer4": 88, "owner_age_estimate": 58, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 20, "years_in_business": 20, "provider_count_estimate": 1, "employee_count_estimate": 4, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Patrick Dennis M-37493 since 2005.", "layer2_comment": "SA premium 78261 Stone Oak edge.", "layer3_comment": "Construction-leaning — verify residential mix.", "layer4_comment": "SA rollup hot + premium +3.", "final_comment": "Swinging D Construction — 20-yr SA premium. C_watch — construction-leaning needs filter check.", "value_add_thesis": "N/A — borderline."},
    "plm-078": {"layer1": 60, "layer2": 60, "layer3": 50, "layer4": 90, "owner_age_estimate": 55, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 33, "years_in_business": 33, "provider_count_estimate": 1, "employee_count_estimate": 6, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.45, "layer1_comment": "Johnny Rooter 2nd-gen Austin since 1993. CAUTION: 'Rooter' name — needs Roto-Rooter franchise verification.", "layer2_comment": "Austin.", "layer3_comment": "Successor check NEGATIVE (2nd-gen).", "layer4_comment": "Austin rollup very hot.", "final_comment": "Johnny Rooter — 2nd-gen Austin. NEEDS Roto-Rooter franchise filter verification. B_forward.", "value_add_thesis": "Forward — verify franchise status first."},
    "plm-080": {"layer1": 45, "layer2": 60, "layer3": 50, "layer4": 90, "owner_age_estimate": 50, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 17, "years_in_business": 17, "provider_count_estimate": 1, "employee_count_estimate": 4, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.40, "layer1_comment": "Plumbinator 2009. Husband+wife.", "layer2_comment": "Round Rock small.", "layer3_comment": "Mid.", "layer4_comment": "Austin/Round Rock rollup very hot.", "final_comment": "The Plumbinator — small Round Rock husband+wife operation. C_watch.", "value_add_thesis": "N/A — too small + young."},
    "plm-081": {"layer1": 70, "layer2": 65, "layer3": 50, "layer4": 90, "owner_age_estimate": 63, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 38, "years_in_business": 38, "provider_count_estimate": 2, "employee_count_estimate": 5, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.55, "layer1_comment": "Sonny+Eric Martinez brothers since 1987.", "layer2_comment": "Pflugerville Austin metro.", "layer3_comment": "Successor check NEGATIVE: 2-brother partnership = mutual successor.", "layer4_comment": "Austin rollup very hot.", "final_comment": "G&M Plumbing — Sonny+Eric brothers Pflugerville. B_forward.", "value_add_thesis": "Forward."},
    "plm-082": {"layer1": 70, "layer2": 65, "layer3": 55, "layer4": 92, "owner_age_estimate": 65, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 45, "years_in_business": 45, "provider_count_estimate": 1, "employee_count_estimate": 6, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.40, "layer1_comment": "Beyond Wow Austin since 1980.", "layer2_comment": "Austin mid.", "layer3_comment": "Mid.", "layer4_comment": "Austin rollup very hot.", "final_comment": "Beyond Wow — 45-yr Austin. B_forward.", "value_add_thesis": "Long-tenured Austin family. Forward."},
    "plm-083": {"layer1": 40, "layer2": 55, "layer3": 50, "layer4": 92, "owner_age_estimate": 50, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 14, "years_in_business": 14, "provider_count_estimate": 1, "employee_count_estimate": 4, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.40, "layer1_comment": "Excalibur Leander 2011.", "layer2_comment": "Leander small.", "layer3_comment": "Modernized.", "layer4_comment": "Austin rollup very hot.", "final_comment": "Excalibur Plumbing — 14-yr Leander, owner too young. D_pass (just past 5-yr-gate, age too young).", "value_add_thesis": "N/A."},
    "plm-084": {"layer1": 78, "layer2": 55, "layer3": 50, "layer4": 90, "owner_age_estimate": 70, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 37, "years_in_business": 37, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Manuel Rodriguez M-17053 since 1988.", "layer2_comment": "N Austin small.", "layer3_comment": "No website. Cap.", "layer4_comment": "Austin rollup hot.", "final_comment": "Crescent Plumbing — long-tenured N Austin MP. C_watch.", "value_add_thesis": "N/A — thin."},
    "plm-086": {"layer1": 60, "layer2": 55, "layer3": 50, "layer4": 92, "owner_age_estimate": 60, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 26, "years_in_business": 26, "provider_count_estimate": 1, "employee_count_estimate": 4, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Martin Jenkins M-20834 since 1999.", "layer2_comment": "Austin NW Hills 78731 premium.", "layer3_comment": "Construction-leaning — verify residential.", "layer4_comment": "Austin rollup very hot + premium +5.", "final_comment": "Gillingwater Construction — 26-yr Austin NW Hills premium. C_watch — construction-leaning needs filter check.", "value_add_thesis": "N/A — borderline."},
    "plm-087": {"layer1": 50, "layer2": 55, "layer3": 50, "layer4": 88, "owner_age_estimate": 55, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 16, "years_in_business": 16, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Isaac Lopez M-39448 since 2009.", "layer2_comment": "E Austin small.", "layer3_comment": "Mid.", "layer4_comment": "Austin rollup very hot.", "final_comment": "Centex Elite Plumbing — 16-yr E Austin small. C_watch.", "value_add_thesis": "N/A — too young."},
    "plm-088": {"layer1": 50, "layer2": 50, "layer3": 50, "layer4": 88, "owner_age_estimate": 55, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 16, "years_in_business": 16, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Eric Campos M-39450 since 2009.", "layer2_comment": "SE Austin. Construction-leaning per legal name.", "layer3_comment": "Mid.", "layer4_comment": "Austin rollup very hot.", "final_comment": "WPM Construction — 16-yr SE Austin construction. C_watch — construction-leaning.", "value_add_thesis": "N/A — borderline."},
    "plm-089": {"layer1": 45, "layer2": 50, "layer3": 50, "layer4": 90, "owner_age_estimate": 45, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 10, "years_in_business": 10, "provider_count_estimate": 1, "employee_count_estimate": 2, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.25, "layer1_comment": "Timothy Kinsey M-41442 since 2015.", "layer2_comment": "Travis small.", "layer3_comment": "Mid.", "layer4_comment": "Austin rollup very hot.", "final_comment": "TK Plumbing — 10-yr Travis, owner too young. D_pass.", "value_add_thesis": "N/A."},
    "plm-090": {"layer1": 70, "layer2": 55, "layer3": 50, "layer4": 90, "owner_age_estimate": 65, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 27, "years_in_business": 27, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Michael Gavit M-20095 since 1998.", "layer2_comment": "Round Rock small.", "layer3_comment": "No website. Cap.", "layer4_comment": "Austin/Round Rock rollup very hot.", "final_comment": "Mike's Plumbing — 27-yr Round Rock MP. C_watch — thin data.", "value_add_thesis": "N/A — thin."},
    "plm-091": {"layer1": 60, "layer2": 50, "layer3": 50, "layer4": 75, "owner_age_estimate": 55, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 18, "years_in_business": 18, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Robert Rocha M-38328 since 2007.", "layer2_comment": "San Marcos Hays exurban Austin.", "layer3_comment": "No website.", "layer4_comment": "Hays exurban -5.", "final_comment": "MAG Plumbing — 18-yr San Marcos. C_watch.", "value_add_thesis": "N/A — exurban."},
    "plm-092": {"layer1": 60, "layer2": 50, "layer3": 50, "layer4": 70, "owner_age_estimate": 55, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 20, "years_in_business": 20, "provider_count_estimate": 1, "employee_count_estimate": 2, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Daniel Mattingly M-37469 since 2005.", "layer2_comment": "Wimberley Hays exurban.", "layer3_comment": "No website.", "layer4_comment": "Hays exurban -5.", "final_comment": "Paisley Plumbing — Wimberley exurban. C_watch.", "value_add_thesis": "N/A — exurban."},
    "plm-093": {"layer1": 70, "layer2": 70, "layer3": 45, "layer4": 70, "owner_age_estimate": 65, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 42, "years_in_business": 42, "provider_count_estimate": 3, "employee_count_estimate": 8, "is_distressed": False, "distress_reasons": [], "confidence": "medium", "data_completeness": 0.50, "layer1_comment": "Lister 3-gen since 1984.", "layer2_comment": "Galveston + HVAC.", "layer3_comment": "Successor check NEGATIVE: 3-gen.", "layer4_comment": "Galveston secondary -3.", "final_comment": "Lister Plumbing — 3-gen Galveston. B_forward.", "value_add_thesis": "Forward."},
    "plm-094": {"layer1": 50, "layer2": 50, "layer3": 50, "layer4": 70, "owner_age_estimate": 50, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 20, "years_in_business": 20, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Kona Plumbing 20+ yrs.", "layer2_comment": "Galveston small.", "layer3_comment": "Mid.", "layer4_comment": "Galveston secondary -3.", "final_comment": "Kona Plumbing — small Galveston. C_watch.", "value_add_thesis": "N/A — secondary metro."},
    "plm-095": {"layer1": 45, "layer2": 50, "layer3": 50, "layer4": 60, "owner_age_estimate": 45, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 20, "years_in_business": 21, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Damian Diaz 20+ yrs.", "layer2_comment": "Beaumont Jefferson — secondary -5.", "layer3_comment": "Mid.", "layer4_comment": "Beaumont secondary -5.", "final_comment": "Beaumont Plumbing — Beaumont secondary. C_watch.", "value_add_thesis": "N/A — secondary metro + young."},
    "plm-096": {"layer1": 50, "layer2": 50, "layer3": 50, "layer4": 60, "owner_age_estimate": 50, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 15, "years_in_business": 15, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.25, "layer1_comment": "Ballard Plumbing.", "layer2_comment": "Beaumont small.", "layer3_comment": "Mid.", "layer4_comment": "Beaumont secondary -5.", "final_comment": "Ballard Plumbing — Beaumont. C_watch — thin.", "value_add_thesis": "N/A — secondary."},
    "plm-097": {"layer1": 50, "layer2": 50, "layer3": 50, "layer4": 88, "owner_age_estimate": 55, "owner_age_source": "unverified", "owner_tenure_years": 20, "years_in_business": 20, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.25, "layer1_comment": "DeWolfe's Plano. Unverified.", "layer2_comment": "Small Plano.", "layer3_comment": "No website.", "layer4_comment": "Collin rollup hot.", "final_comment": "DeWolfe's Affordable Plumbing — Plano, no website, unverified. C_watch.", "value_add_thesis": "N/A — thin."},
    "plm-098": {"layer1": 55, "layer2": 55, "layer3": 50, "layer4": 88, "owner_age_estimate": 55, "owner_age_source": "biz_history_proxy", "owner_tenure_years": 25, "years_in_business": 25, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.35, "layer1_comment": "Best Quality Plano. Senior MP 25 yrs.", "layer2_comment": "Plano small.", "layer3_comment": "Mid.", "layer4_comment": "Collin rollup hot.", "final_comment": "Best Quality Plumbing — Plano family. B_forward.", "value_add_thesis": "Plano Collin family. Forward."},
    "plm-100": {"layer1": 55, "layer2": 60, "layer3": 50, "layer4": 85, "owner_age_estimate": 55, "owner_age_source": "license_tenure_proxy", "owner_tenure_years": 20, "years_in_business": 20, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.30, "layer1_comment": "Jeffery Bartsch M-37279 since 2005.", "layer2_comment": "The Woodlands Montgomery.", "layer3_comment": "No website.", "layer4_comment": "Houston rollup hot.", "final_comment": "Bartsch Services — 20-yr Woodlands MP. C_watch.", "value_add_thesis": "N/A — thin."},
}

# Merge
ALL_SCORES = {**DEFAULT_SCORES, **SCORES}

def compute_final(s):
    """Apply weights and tier rules."""
    layer1 = s["layer1"]
    layer2 = s["layer2"]
    layer3 = s["layer3"]
    layer4 = s["layer4"]

    # Hard gates
    if s.get("is_distressed", False):
        return 25, "D_pass", "distressed_or_excluded"

    if s.get("years_in_business") is not None and s["years_in_business"] < 5:
        # Cap at C_watch / 35
        weighted = round(0.30 * layer1 + 0.25 * layer2 + 0.30 * layer3 + 0.15 * layer4)
        return min(weighted, 35), "C_watch" if weighted >= 35 else "D_pass", "under_5_yrs_cap"

    weighted = round(0.30 * layer1 + 0.25 * layer2 + 0.30 * layer3 + 0.15 * layer4)

    confidence = s.get("confidence", "low")

    # A_acquire_self gates
    if weighted >= 78 and layer1 >= 70 and layer3 >= 65 and confidence in ("medium", "high"):
        return weighted, "A_acquire_self", "passed_a_gates"

    # B_forward
    if weighted >= 60:
        return weighted, "B_forward", "b_tier"

    # C_watch
    if weighted >= 45:
        return weighted, "C_watch", "c_tier"

    # D_pass
    return weighted, "D_pass", "d_tier"

# Load spine
with open(DATA / "plumbing_spine.json") as f:
    spine = json.load(f)

# Build businesses + scores
businesses_output = []
csv_rows = []
tier_counts = {"A_acquire_self": 0, "B_forward": 0, "C_watch": 0, "D_pass": 0}
distress_count = 0

for spine_entry in spine:
    spine_id = spine_entry["spine_id"]
    s = ALL_SCORES.get(spine_id)
    if not s:
        # Default fallback for any missing
        s = {"layer1": 50, "layer2": 50, "layer3": 45, "layer4": 75, "owner_age_estimate": None, "owner_age_source": "unverified", "owner_tenure_years": None, "years_in_business": None, "provider_count_estimate": 1, "employee_count_estimate": 3, "is_distressed": False, "distress_reasons": [], "confidence": "low", "data_completeness": 0.20, "layer1_comment": "Unverified.", "layer2_comment": "Unverified.", "layer3_comment": "Unverified.", "layer4_comment": "TX baseline.", "final_comment": "Unverified candidate. C_watch pending enrichment.", "value_add_thesis": "N/A — unverified."}

    final_score, final_tier, tier_reason = compute_final(s)
    if s.get("is_distressed", False):
        distress_count += 1
    tier_counts[final_tier] = tier_counts.get(final_tier, 0) + 1

    biz_id = str(uuid.uuid5(uuid.NAMESPACE_URL, f"offmarket:plumbing:{spine_entry['legal_name']}:{spine_entry.get('city', '')}"))

    business = {
        "id": biz_id,
        "spine_id": spine_id,
        "vertical": "plumbing",
        "legal_name": spine_entry["legal_name"],
        "dba_name": spine_entry.get("dba_name"),
        "naics_code": "238220",
        "address": spine_entry.get("address"),
        "city": spine_entry.get("city"),
        "county": spine_entry.get("county"),
        "state": spine_entry.get("state", "TX"),
        "zip": spine_entry.get("zip"),
        "phone": spine_entry.get("phone"),
        "website": spine_entry.get("website"),
        "license_number": spine_entry.get("license_number"),
        "license_type": spine_entry.get("license_type"),
        "license_status": "Current" if "license_number" in spine_entry else None,
        "license_issue_date": spine_entry.get("license_issue_date"),
        "license_holder_name": spine_entry.get("license_holder_name"),
        "entity_status": None,  # Comptroller not directly verified
        "registered_agent": None,
        "owner_name": spine_entry.get("license_holder_name"),
        "owner_age_estimate": s.get("owner_age_estimate"),
        "owner_age_source": s.get("owner_age_source"),
        "owner_tenure_years": s.get("owner_tenure_years"),
        "owner_homestead_address": None,
        "owner_property_deed_date": None,
        "years_in_business": s.get("years_in_business") or (2026 - spine_entry["year_established"] if spine_entry.get("year_established") else None),
        "employee_count_estimate": s.get("employee_count_estimate"),
        "provider_count_estimate": s.get("provider_count_estimate"),
        "employee_count_source": "website_team_page_or_buildzoom_or_dnb",
        "is_distressed": s.get("is_distressed", False),
        "distress_reasons": s.get("distress_reasons", []),
        "data_sources": spine_entry.get("data_sources", []),
        "platform_affiliation_check": spine_entry.get("platform_affiliation_check"),
        "verification_notes": spine_entry.get("verification_notes"),
        "scores": {
            "layer1_base_rate": s["layer1"],
            "layer1_comment": s["layer1_comment"],
            "layer2_sellability": s["layer2"],
            "layer2_comment": s["layer2_comment"],
            "layer3_behavioral_trigger": s["layer3"],
            "layer3_comment": s["layer3_comment"],
            "layer4_market_pull": s["layer4"],
            "layer4_comment": s["layer4_comment"],
            "final_score": final_score,
            "final_tier": final_tier,
            "tier_reason": tier_reason,
            "final_comment": s["final_comment"],
            "value_add_thesis": s["value_add_thesis"],
            "confidence": s.get("confidence", "low"),
            "data_completeness": s.get("data_completeness", 0.3),
        }
    }
    businesses_output.append(business)

    # CSV row
    csv_rows.append({
        "legal_name": business["legal_name"],
        "dba_name": business["dba_name"] or "",
        "city": business["city"] or "",
        "county": business["county"] or "",
        "zip": business["zip"] or "",
        "address": business["address"] or "",
        "phone": business["phone"] or "",
        "website": business["website"] or "",
        "owner_name": business["owner_name"] or "",
        "owner_age_estimate": business["owner_age_estimate"] or "",
        "owner_age_source": business["owner_age_source"] or "",
        "owner_tenure_years": business["owner_tenure_years"] or "",
        "years_in_business": business["years_in_business"] or "",
        "provider_count_estimate": business["provider_count_estimate"] or "",
        "employee_count_estimate": business["employee_count_estimate"] or "",
        "is_distressed": business["is_distressed"],
        "distress_reasons": json.dumps(business["distress_reasons"]),
        "layer1_base_rate": business["scores"]["layer1_base_rate"],
        "layer1_comment": business["scores"]["layer1_comment"],
        "layer2_sellability": business["scores"]["layer2_sellability"],
        "layer2_comment": business["scores"]["layer2_comment"],
        "layer3_behavioral_trigger": business["scores"]["layer3_behavioral_trigger"],
        "layer3_comment": business["scores"]["layer3_comment"],
        "layer4_market_pull": business["scores"]["layer4_market_pull"],
        "layer4_comment": business["scores"]["layer4_comment"],
        "final_score": business["scores"]["final_score"],
        "final_tier": business["scores"]["final_tier"],
        "final_comment": business["scores"]["final_comment"],
        "value_add_thesis": business["scores"]["value_add_thesis"],
        "confidence": business["scores"]["confidence"],
        "data_completeness": business["scores"]["data_completeness"],
    })

# Write JSON
out = {
    "score_run": {
        "run_label": RUN_LABEL,
        "score_run_id": SCORE_RUN_ID,
        "model_version": MODEL_VERSION,
        "weights": WEIGHTS,
        "vertical": VERTICAL,
        "geography": "TX — Harris/Dallas/Tarrant/Bexar/Travis priority + secondary metros",
        "generated_at": "2026-05-16T00:00:00Z",
        "counts": {
            "spine_rows": len(spine),
            "scored": len(businesses_output),
            "tier_a": tier_counts.get("A_acquire_self", 0),
            "tier_b": tier_counts.get("B_forward", 0),
            "tier_c": tier_counts.get("C_watch", 0),
            "tier_d": tier_counts.get("D_pass", 0),
            "distress_excluded": distress_count,
        }
    },
    "businesses": businesses_output
}

with open(DATA / "plumbing_targets.json", "w") as f:
    json.dump(out, f, indent=2)

# Write CSV
csv_fields = [
    "legal_name", "dba_name", "city", "county", "zip", "address", "phone", "website",
    "owner_name", "owner_age_estimate", "owner_age_source", "owner_tenure_years",
    "years_in_business", "provider_count_estimate", "employee_count_estimate",
    "is_distressed", "distress_reasons",
    "layer1_base_rate", "layer1_comment", "layer2_sellability", "layer2_comment",
    "layer3_behavioral_trigger", "layer3_comment", "layer4_market_pull", "layer4_comment",
    "final_score", "final_tier", "final_comment", "value_add_thesis",
    "confidence", "data_completeness"
]
with open(DATA / "plumbing_targets.csv", "w", newline="") as f:
    w = csv.DictWriter(f, fieldnames=csv_fields)
    w.writeheader()
    for row in csv_rows:
        w.writerow(row)

# Sort businesses by final_score desc for top-15 display
sorted_bizs = sorted(businesses_output, key=lambda b: b["scores"]["final_score"], reverse=True)

print(f"=== PLUMBING SCORING COMPLETE ===")
print(f"Spine: {len(spine)} rows")
print(f"Scored: {len(businesses_output)} rows")
print(f"Tier A_acquire_self: {tier_counts.get('A_acquire_self', 0)}")
print(f"Tier B_forward:       {tier_counts.get('B_forward', 0)}")
print(f"Tier C_watch:         {tier_counts.get('C_watch', 0)}")
print(f"Tier D_pass:          {tier_counts.get('D_pass', 0)}")
print(f"Distressed (incl D):  {distress_count}")
print()
print("=== TOP 15 BY FINAL SCORE ===")
for i, b in enumerate(sorted_bizs[:15]):
    print(f"{i+1:2d}. {b['legal_name']:50s} | {b['city']:18s} | {b['scores']['final_tier']:18s} | final={b['scores']['final_score']:3d} | L1={b['scores']['layer1_base_rate']:3d} L2={b['scores']['layer2_sellability']:3d} L3={b['scores']['layer3_behavioral_trigger']:3d} L4={b['scores']['layer4_market_pull']:3d}")
